### ISSUE TITLE
Does not load current version of Juriscraper

### ISSUE THREAD

**Issue by snorey** [freelawproject/freelawmachine#25]
After going through the Freelawmachine installation process, starting the server and attempting to access it at localhost:8000, I received the following error:

```
Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/vagrant/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 365, in resolve
    for pattern in self.url_patterns:
  File "/home/vagrant/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 401, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/vagrant/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 395, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/var/www/courtlistener/cl/urls.py", line 19, in <module>
    url('', include('cl.api.urls')),
  File "/home/vagrant/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/var/www/courtlistener/cl/api/urls.py", line 9, in <module>
    from cl.recap import views as recap_views
  File "/var/www/courtlistener/cl/recap/views.py", line 6, in <module>
    from cl.recap.tasks import process_recap_upload
  File "/var/www/courtlistener/cl/recap/tasks.py", line 13, in <module>
    from cl.lib.pacer import map_cl_to_pacer_id, normalize_attorney_contact, \
  File "/var/www/courtlistener/cl/lib/pacer.py", line 16, in <module>
    from juriscraper.lib.exceptions import ParsingException
ImportError: No module named exceptions
```
It looks like Freelawmachine is loaded with an older version of Juriscraper which doesn't contain the "exceptions" and "docket_utils" libraries that Courtlistener wants.

I was able to get past the error and reach the expected Courtlistener page by replacing the installed Juriscraper (which appears to be dated January 27, 2017) with the current version from Github.

**Comment by voutilad** [comment]
@mlissner could this be a dependency issue between CL master's requirements.txt and what's in PyPI for Juriscraper? Looks like CL's not using a frozen version of Juriscraper: https://github.com/freelawproject/courtlistener/blob/master/requirements.txt#L46

**Comment by mlissner** [comment]
Just updating both CL and Juriscraper should fix this. It's not version locked because CL should always work on the latest version of JS.

**Comment by mlissner** [comment]
Hm. I think we're good with this one now that #26 is merged, unless there's a way to upgrade everything as part of the install (and that's a good idea).
