### ISSUE TITLE
seal_rookery package cannot be imported

### ISSUE THREAD

**Issue by janderse** [freelawproject/freelawmachine#5]
Importing seal_rookery fails because the package is installed in the wrong directory in the VM.

Repro:
```
vagrant up
vagrant ssh
cd /var/www/courtlistener
./manage.py cl_scrape_opinions   --courts juriscraper.opinions.united_states.federal_appellate.ca1   --rate 5
```
Cause:
Currently `/usr/lib/python2.7/dist-packages/seal_rookery` points to `/usr/local/seal_rookery`.  But look at what is in `/usr/local/seal_rookery`:
```
vagrant@freelawbox:/var/www/courtlistener$ ls -al /usr/local/seal_rookery/
total 72
drwxr-xr-x  4 root root  4096 Jun 10 11:10 .
drwxr-xr-x 17 root root  4096 Jun 10 11:14 ..
-rw-r--r--  1 root root 12385 Jun 10 11:10 ez_setup.py
drwxr-xr-x  8 root root  4096 Jun 10 11:10 .git
-rw-r--r--  1 root root   725 Jun 10 11:10 .gitignore
-rw-r--r--  1 root root  1830 Jun 10 11:10 LICENSE.txt
-rw-r--r--  1 root root   341 Jun 10 11:10 MANIFEST.in
-rw-r--r--  1 root root  4588 Jun 10 11:10 README.rst
-rw-r--r--  1 root root     6 Jun 10 11:10 requirements-dev.txt
-rw-r--r--  1 root root    11 Jun 10 11:10 requirements.txt
drwxr-xr-x  4 root root  4096 Jun 10 11:10 seal_rookery
-rw-r--r--  1 root root    41 Jun 10 11:10 setup.cfg
-rw-r--r--  1 root root  2589 Jun 10 11:10 setup.py
-rw-r--r--  1 root root  1077 Jun 10 11:10 test.py
```

The Python package is actually at `/usr/local/seal_rookery/seal_rookery`.  So either the symbolic link or the git root needs to change so that it lines up properly.

Stack trace:
```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 190, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/var/www/courtlistener/cl/scrapers/management/commands/cl_scrape_opinions.py", line 24, in <module>
    from cl.scrapers.tasks import extract_doc_content, extract_by_ocr
  File "/var/www/courtlistener/cl/scrapers/tasks.py", line 16, in <module>
    from seal_rookery import seals_data, seals_root
ImportError: No module named seal_rookery
```

**Comment by voutilad** [comment]
I'm working on a new release and will address the seal_rookery issue above. Thanks!

**Comment by voutilad** [comment]
This are looking good so far in the `develop` branch. The upcoming `1.6.0` version should fix this.

**Comment by voutilad** [comment]
Resolved in the `develop` branch and will be in next release.
